apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: my-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-v1
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app:  my-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
        - image: gcr.io/wave-235114/app:1.0
          imagePullPolicy: Always
          name: my-app
          ports:
            - containerPort: 8080

---
  
# API BUG

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-v2
  labels:
    app: my-app
spec:
  selector:
    matchLabels:
      app:  my-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: my-app
        version: v2
    spec:
      containers:
        - image: gcr.io/wave-235114/app:4.0
          imagePullPolicy: Always
          name: my-app
          ports:
            - containerPort: 8080